mkdir flatiron
cd flatiron
mkdir mod1
mkdir mod2
mkdir mod3
mkdir mod4
mkdir mod5

cd mod1
git clone git@github.com:FluxOfPingIntegers/020121-Intro-to-Arrays-And-Iteration
git clone git@github.com:FluxOfPingIntegers/looping-while-until
git clone git@github.com:FluxOfPingIntegers/reverse-each-word
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-attribute-accessors-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-has-many-through-lab
git clone git@github.com:FluxOfPingIntegers/anagram-detector
git clone git@github.com:FluxOfPingIntegers/method-arguments-lab
git clone git@github.com:FluxOfPingIntegers/ruby-building-applications-gems-and-bundler
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-classes-and-instances-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-kickstarter-lab
git clone git@github.com:FluxOfPingIntegers/apples-and-holidays
git clone git@github.com:FluxOfPingIntegers/method-scope-lab
git clone git@github.com:FluxOfPingIntegers/ruby-building-applications-requiring-files
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-email-parser-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-my-pets
git clone git@github.com:FluxOfPingIntegers/array-CRUD-lab
git clone git@github.com:FluxOfPingIntegers/my-collect
git clone git@github.com:FluxOfPingIntegers/ruby-building-applications-setting-up-the-environment
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-instance-methods-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-self-cash-register-lab
git clone git@github.com:FluxOfPingIntegers/array-methods-lab
git clone git@github.com:FluxOfPingIntegers/my-each
git clone git@github.com:FluxOfPingIntegers/ruby-getting-remote-data-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-instance-variables-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-self-count-sentences-lab
git clone git@github.com:FluxOfPingIntegers/badges-and-schedules
git clone git@github.com:FluxOfPingIntegers/my-first-hash
git clone git@github.com:FluxOfPingIntegers/ruby-intro-to-hashes-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-object-attributes-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-self-person-lab
git clone git@github.com:FluxOfPingIntegers/building-nested-hashes
git clone git@github.com:FluxOfPingIntegers/my_all
git clone git@github.com:FluxOfPingIntegers/ruby-metaprogramming-custom-errors
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-object-initialization-lab
git clone git@github.com:FluxOfPingIntegers/ruby-remote-data-practice-scraping
git clone git@github.com:FluxOfPingIntegers/cartoon-collections
git clone git@github.com:FluxOfPingIntegers/my_find_code_along
git clone git@github.com:FluxOfPingIntegers/ruby-metaprogramming-mass-assignment-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-defining-inheritance
git clone git@github.com:FluxOfPingIntegers/ruby-variable-assignment
git clone git@github.com:FluxOfPingIntegers/collections_practice
git clone git@github.com:FluxOfPingIntegers/nested-hash-iteration-code-along
git clone git@github.com:FluxOfPingIntegers/ruby-metaprogramming-triangle-classification-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-inheritance-lab
git clone git@github.com:FluxOfPingIntegers/say-hello-ruby
git clone git@github.com:FluxOfPingIntegers/countdown-to-midnight
git clone git@github.com:FluxOfPingIntegers/oo-tic-tac-toe
git clone git@github.com:FluxOfPingIntegers/ruby-methods-readme
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-modules
git clone git@github.com:FluxOfPingIntegers/scraping-flatiron-code-along
git clone git@github.com:FluxOfPingIntegers/debugging-with-pry
git clone git@github.com:FluxOfPingIntegers/operators
git clone git@github.com:FluxOfPingIntegers/ruby-music-library-cli
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-modules-lab
git clone git@github.com:FluxOfPingIntegers/scraping-kickstarter
git clone git@github.com:FluxOfPingIntegers/deli-counter
git clone git@github.com:FluxOfPingIntegers/other-hash-methods-code-along
git clone git@github.com:FluxOfPingIntegers/ruby-oo-advanced-class-methods-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-super-lab
git clone git@github.com:FluxOfPingIntegers/simple-nesting
git clone git@github.com:FluxOfPingIntegers/getting-remote-data-working-with-apis
git clone git@github.com:FluxOfPingIntegers/oxford-comma
git clone git@github.com:FluxOfPingIntegers/ruby-oo-advanced-class-methods-puppy-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-banking-lab
git clone git@github.com:FluxOfPingIntegers/speaking-grandma
git clone git@github.com:FluxOfPingIntegers/hash-iteration
git clone git@github.com:FluxOfPingIntegers/parrot-ruby
git clone git@github.com:FluxOfPingIntegers/ruby-oo-class-variables-and-class-methods-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-belongs-to-lab
git clone git@github.com:FluxOfPingIntegers/square_array
git clone git@github.com:FluxOfPingIntegers/intro-to-OO
git clone git@github.com:FluxOfPingIntegers/phase1_project
git clone git@github.com:FluxOfPingIntegers/ruby-oo-class-variables-class-constants
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-collaborating-objects-lab
git clone git@github.com:FluxOfPingIntegers/welcome-completing-assignments
git clone git@github.com:FluxOfPingIntegers/key-for-min-value
git clone git@github.com:FluxOfPingIntegers/prime-ruby
git clone git@github.com:FluxOfPingIntegers/ruby-oo-complex-objects-putting-the-pieces-together
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-has-many-lab
git clone git@github.com:FluxOfPingIntegers/yield-and-blocks
git clone git@github.com:FluxOfPingIntegers/looping-times
git clone git@github.com:FluxOfPingIntegers/regex-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-complex-objects-school-domain
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-has-many-through
git clone git@github.com:FluxOfPingIntegers/yield-and-return-values
cd ..

cd mod2
git clone git@github.com:FluxOfPingIntegers/Phase2_Project
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-issue-bot-9000
git clone git@github.com:FluxOfPingIntegers/nyc-sinatra
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-forms-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-nested-forms
git clone git@github.com:FluxOfPingIntegers/active-record-associations-and-migrations
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-kitten-wheelbarrow-lab
git clone git@github.com:FluxOfPingIntegers/orms-bringing-it-all-together
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-routes-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-nested-forms-lab-superheros
git clone git@github.com:FluxOfPingIntegers/active-record-associations-methods
git clone git@github.com:FluxOfPingIntegers/css-essentials-introduction-to-css-lab
git clone git@github.com:FluxOfPingIntegers/orms-mapping-classes-to-database-tables-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-sessions-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-password-security
git clone git@github.com:FluxOfPingIntegers/active-record-associations-tvland-lab
git clone git@github.com:FluxOfPingIntegers/css-essentials-my-little-rainbow-lab
git clone git@github.com:FluxOfPingIntegers/orms-mapping-database-records-to-ruby-objects-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-views-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-restful-routes-lab
git clone git@github.com:FluxOfPingIntegers/active-record-costume-store-lab
git clone git@github.com:FluxOfPingIntegers/dynamic-orm-inheritance
git clone git@github.com:FluxOfPingIntegers/orms-pokemon-scraper
git clone git@github.com:FluxOfPingIntegers/sinatra-basics
git clone git@github.com:FluxOfPingIntegers/sinatra-secure-password-lab
git clone git@github.com:FluxOfPingIntegers/active-record-crud-operations-lab
git clone git@github.com:FluxOfPingIntegers/dynamic-orm-lab
git clone git@github.com:FluxOfPingIntegers/orms-updating-records-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-complex-forms-associations
git clone git@github.com:FluxOfPingIntegers/sinatra-sessions
git clone git@github.com:FluxOfPingIntegers/active-record-intro-to-rake
git clone git@github.com:FluxOfPingIntegers/dynamic-orms-readme
git clone git@github.com:FluxOfPingIntegers/rack-dynamic-routes-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-dynamic-routes-codealong
git clone git@github.com:FluxOfPingIntegers/sinatra-shotgun-server
git clone git@github.com:FluxOfPingIntegers/active-record-migrations
git clone git@github.com:FluxOfPingIntegers/html-basics-a-tag-with-href-attributes-lab
git clone git@github.com:FluxOfPingIntegers/rack-dynamic-web-apps
git clone git@github.com:FluxOfPingIntegers/sinatra-dynamic-routes-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-user-auth
git clone git@github.com:FluxOfPingIntegers/active-record-querying-methods-lab
git clone git@github.com:FluxOfPingIntegers/html-basics-well-formed-html-document-lab
git clone git@github.com:FluxOfPingIntegers/rack-get-params-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-forms-params-readme-walkthrough
git clone git@github.com:FluxOfPingIntegers/sinatra-view-and-controller-readme-walkthrough
git clone git@github.com:FluxOfPingIntegers/active-record-translating-from-orm-to-ar
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-images-lab
git clone git@github.com:FluxOfPingIntegers/rack-intro
git clone git@github.com:FluxOfPingIntegers/sinatra-from-scratch-readme
git clone git@github.com:FluxOfPingIntegers/sinatra-views
git clone git@github.com:FluxOfPingIntegers/active-record-writing-migrations-lab
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-links-lab
git clone git@github.com:FluxOfPingIntegers/rack-responses-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-hello-world-basics
git clone git@github.com:FluxOfPingIntegers/sinatra-views-lab
git clone git@github.com:FluxOfPingIntegers/basic-sinatra-forms-lab
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-lists-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-activerecord-associations
git clone git@github.com:FluxOfPingIntegers/sinatra-integrating-models-walkthrough
git clone git@github.com:FluxOfPingIntegers/sql-aggregate-functions-lab
git clone git@github.com:FluxOfPingIntegers/code-along
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-tables-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-activerecord-setup
git clone git@github.com:FluxOfPingIntegers/sinatra-logging-in-and-out
git clone git@github.com:FluxOfPingIntegers/sql-organizing-bears-lab
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-fundamentals-lab
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-text-formatting-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-activerecord-using-tux
git clone git@github.com:FluxOfPingIntegers/sinatra-mvc-file-structure
git clone git@github.com:FluxOfPingIntegers/sql-table-relations-crowdfunding-join-table-lab
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-graffiti-override-lab
git clone git@github.com:FluxOfPingIntegers/intro-to-capybara
git clone git@github.com:FluxOfPingIntegers/sinatra-ar-crud-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-mvc-lab
git clone git@github.com:FluxOfPingIntegers/sql-table-relations-library-lab
cd ..

cd mod3
git clone git@github.com:FluxOfPingIntegers/activerecord-lifecycle-reading
git clone git@github.com:FluxOfPingIntegers/activerecord-validations-lab
git clone git@github.com:FluxOfPingIntegers/basic-nested-forms
git clone git@github.com:FluxOfPingIntegers/basic-nested-forms-lab
git clone git@github.com:FluxOfPingIntegers/blog-flash
git clone git@github.com:FluxOfPingIntegers/cookies_and_sessions_lab
git clone git@github.com:FluxOfPingIntegers/displaying-associations-rails
git clone git@github.com:FluxOfPingIntegers/displaying-associations-rails-lab
git clone git@github.com:FluxOfPingIntegers/displaying-has-many-through-rails
git clone git@github.com:FluxOfPingIntegers/displaying-has-many-through-rails-lab
git clone git@github.com:FluxOfPingIntegers/flatiron-bnb-associations
git clone git@github.com:FluxOfPingIntegers/flatiron-kitchen
git clone git@github.com:FluxOfPingIntegers/forms-and-basic-associations-rails-lab
git clone git@github.com:FluxOfPingIntegers/has-many-through-forms-rails
git clone git@github.com:FluxOfPingIntegers/has-many-through-forms-rails-labs
git clone git@github.com:FluxOfPingIntegers/has_secure_password_lab
git clone git@github.com:FluxOfPingIntegers/join-the-fun-rails
git clone git@github.com:FluxOfPingIntegers/login_required_lab
git clone git@github.com:FluxOfPingIntegers/model-class-methods-lab
git clone git@github.com:FluxOfPingIntegers/model-class-methods-reading
git clone git@github.com:FluxOfPingIntegers/modification-nested-routes-lab
git clone git@github.com:FluxOfPingIntegers/modification-nested-routes-reading
git clone git@github.com:FluxOfPingIntegers/namespaced-routes-lab
git clone git@github.com:FluxOfPingIntegers/namespaced-routes-reading
git clone git@github.com:FluxOfPingIntegers/omniauth_lab
git clone git@github.com:FluxOfPingIntegers/omniauth_readme
git clone git@github.com:FluxOfPingIntegers/partial-locals-lab
git clone git@github.com:FluxOfPingIntegers/partial-locals-reading
mkdir phase-3-project
cd phase-3-project
git clone git@github.com:FluxOfPingIntegers/crate_digger
cd ..
git clone git@github.com:FluxOfPingIntegers/rails-activerecord-model-rails-lab
git clone git@github.com:FluxOfPingIntegers/rails-activerecord-models-and-rails-readme
git clone git@github.com:FluxOfPingIntegers/rails-amusement-park
git clone git@github.com:FluxOfPingIntegers/rails-blog-associations-validations
git clone git@github.com:FluxOfPingIntegers/rails-blog-nested-forms
git clone git@github.com:FluxOfPingIntegers/rails-create-action-lab
git clone git@github.com:FluxOfPingIntegers/rails-create-action-readme
git clone git@github.com:FluxOfPingIntegers/rails-cru-form_for-lab
git clone git@github.com:FluxOfPingIntegers/rails-dynamic-request-lab
git clone git@github.com:FluxOfPingIntegers/rails-dynamic-request-readme
git clone git@github.com:FluxOfPingIntegers/rails-edit-update-action-readme
git clone git@github.com:FluxOfPingIntegers/rails-form_for-lab
git clone git@github.com:FluxOfPingIntegers/rails-form_for-on-edit-readme
git clone git@github.com:FluxOfPingIntegers/rails-form_tag-lab
git clone git@github.com:FluxOfPingIntegers/rails-form_tag-readme
git clone git@github.com:FluxOfPingIntegers/rails-generators-readme
git clone git@github.com:FluxOfPingIntegers/rails-hello-world-lab
git clone git@github.com:FluxOfPingIntegers/rails-index-show-new-create-lab
git clone git@github.com:FluxOfPingIntegers/rails-layouts-and-templates-lab
git clone git@github.com:FluxOfPingIntegers/rails-mini-project
git clone git@github.com:FluxOfPingIntegers/rails-programmer-profile-partials
git clone git@github.com:FluxOfPingIntegers/rails-restful-index-action-lab
git clone git@github.com:FluxOfPingIntegers/rails-static-request-readme
git clone git@github.com:FluxOfPingIntegers/rails-url-helpers-readme
git clone git@github.com:FluxOfPingIntegers/refactoring-views-with-helpers-lab
git clone git@github.com:FluxOfPingIntegers/refactoring-views-with-helpers-reading
git clone git@github.com:FluxOfPingIntegers/rendering-collections-lab
git clone git@github.com:FluxOfPingIntegers/rendering-collections-reading
git clone git@github.com:FluxOfPingIntegers/routing-nested-resources-lab
git clone git@github.com:FluxOfPingIntegers/routing-nested-resources-reading
git clone git@github.com:FluxOfPingIntegers/sessions_controller_lab
git clone git@github.com:FluxOfPingIntegers/simple-partials-lab
git clone git@github.com:FluxOfPingIntegers/simple-partials-reading
git clone git@github.com:FluxOfPingIntegers/strong-params-basics
git clone git@github.com:FluxOfPingIntegers/validations-in-controller-actions-rails-lab
git clone git@github.com:FluxOfPingIntegers/validations-with-form_tag-rails-lab
cd ..

cd mod4
git clone git@github.com:FluxOfPingIntegers/fewpjs-acting-on-events
git clone git@github.com:FluxOfPingIntegers/fewpjs-adding-behavior-with-methods
git clone git@github.com:FluxOfPingIntegers/fewpjs-build-the-example
git clone git@github.com:FluxOfPingIntegers/fewpjs-class-extensions-extends-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-class-extensions-super-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-document-onload
git clone git@github.com:FluxOfPingIntegers/fewpjs-dom-editing-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-event-listening
git clone git@github.com:FluxOfPingIntegers/fewpjs-fetch-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-fns-as-first-class-data-array-o-functions
git clone git@github.com:FluxOfPingIntegers/fewpjs-fns-as-first-class-data-do-behavior
git clone git@github.com:FluxOfPingIntegers/fewpjs-getter-and-setter-methods
git clone git@github.com:FluxOfPingIntegers/fewpjs-iterators-fndcl-fnexpr-filter-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-iterators-fndcl-fnexpr-find-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-iterators-fndcl-fnexpr-map-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-iterators-fndcl-fnexpr-reduce-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-js-fundamentals-arithmetic-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-oo-initializing-instances
git clone git@github.com:FluxOfPingIntegers/fewpjs-oo-static-methods-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-removing-altering-and-inserting-html-lab
git clone git@github.com:FluxOfPingIntegers/fewpjs-sending-data-with-fetch
git clone git@github.com:FluxOfPingIntegers/fewpjs-stitching-together-the-three-pillars-new
git clone git@github.com:FluxOfPingIntegers/fewpjs_arrow_function_shorthand
git clone git@github.com:FluxOfPingIntegers/fewpjs_destructuring_assignment
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-basic-functions-review-lab
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-context-lab
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-first-class-functions-lab
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-functional-library-project
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-generalized-map-and-reduce-lab
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-introduction-to-context-lab
git clone git@github.com:FluxOfPingIntegers/js-advanced-functions-introduction-to-map-and-reduce-lab
git clone git@github.com:FluxOfPingIntegers/js-basics-variables-lab
git clone git@github.com:FluxOfPingIntegers/js-data-structures-arrays-lab
git clone git@github.com:FluxOfPingIntegers/js-data-structures-objects-lab
git clone git@github.com:FluxOfPingIntegers/js-looping-and-iteration-looping-code-along
git clone git@github.com:FluxOfPingIntegers/js-object-oriented-constructor-functions-lab
git clone git@github.com:FluxOfPingIntegers/js-principles-scope-lab
git clone git@github.com:FluxOfPingIntegers/js-rails-as-api-custom-json-rendering-using-rails
git clone git@github.com:FluxOfPingIntegers/js-rails-as-api-extracting-a-service-class
git clone git@github.com:FluxOfPingIntegers/js-rails-as-api-rendering-different-content-types-using-rails
git clone git@github.com:FluxOfPingIntegers/js-rails-as-api-rendering-related-object-data-in-json
git clone git@github.com:FluxOfPingIntegers/js-rails-as-api-review-of-rails-mvc
git clone git@github.com:FluxOfPingIntegers/js-rails-as-api-using-fast-json-api
git clone git@github.com:FluxOfPingIntegers/jsdom-dom-challenge
git clone git@github.com:FluxOfPingIntegers/jsdom-fetch-dog-ceo-challenge
git clone git@github.com:FluxOfPingIntegers/jsdom-task-lister-lite
git clone git@github.com:FluxOfPingIntegers/jsdom-toy-tale
mkdir phase-4-project
cd phase-4-project
git clone git@github.com:FluxOfPingIntegers/congo_api
git clone git@github.com:FluxOfPingIntegers/congo_client
cd ..
git clone git@github.com:FluxOfPingIntegers/prototypal-oo-js-object-oriented-object-methods-lab
cd ..

cd mod5
git clone git@github.com:FluxOfPingIntegers/a-react-app-example
git clone git@github.com:FluxOfPingIntegers/building-forms-lab
git clone git@github.com:FluxOfPingIntegers/combine-reducers
git clone git@github.com:FluxOfPingIntegers/create-react-app-readme
git clone git@github.com:FluxOfPingIntegers/crud-lab
git clone git@github.com:FluxOfPingIntegers/hogwarts
git clone git@github.com:FluxOfPingIntegers/intro-to-redux-library-codealong
git clone git@github.com:FluxOfPingIntegers/jwt-auth-rails
git clone git@github.com:FluxOfPingIntegers/map-dispatch-to-props-lab
git clone git@github.com:FluxOfPingIntegers/map-dispatch-to-props-readme
git clone git@github.com:FluxOfPingIntegers/map-state-to-props-lab
git clone git@github.com:FluxOfPingIntegers/map-state-to-props-readme
git clone git@github.com:FluxOfPingIntegers/npm-lab
mkdir phase-5-project
cd phase-5-project
git clone git@github.com:FluxOfPingIntegers/sproutable-backend
git clone git@github.com:FluxOfPingIntegers/sproutable-frontend
cd ..
git clone git@github.com:FluxOfPingIntegers/quote-maker-react-lab
git clone git@github.com:FluxOfPingIntegers/react-async-fetch-lab
git clone git@github.com:FluxOfPingIntegers/react-async-gif-search-lab
git clone git@github.com:FluxOfPingIntegers/react-component-mounting-and-unmounting-lab
git clone git@github.com:FluxOfPingIntegers/react-component-mounting-lab
git clone git@github.com:FluxOfPingIntegers/react-component-updating-lab
git clone git@github.com:FluxOfPingIntegers/react-components-as-routes
git clone git@github.com:FluxOfPingIntegers/react-components-as-routes-lab
git clone git@github.com:FluxOfPingIntegers/react-container-components-lab
git clone git@github.com:FluxOfPingIntegers/react-dynamic-components-lab
git clone git@github.com:FluxOfPingIntegers/react-event-system-lab
git clone git@github.com:FluxOfPingIntegers/react-events-crash-course-lab
git clone git@github.com:FluxOfPingIntegers/react-events-in-detail-lab
git clone git@github.com:FluxOfPingIntegers/react-forms-lab
git clone git@github.com:FluxOfPingIntegers/react-information-flow-code-along
git clone git@github.com:FluxOfPingIntegers/react-initial-state-lab
git clone git@github.com:FluxOfPingIntegers/react-presentation-components-lab
git clone git@github.com:FluxOfPingIntegers/react-props-and-state-lab
git clone git@github.com:FluxOfPingIntegers/react-props-movie-lab
git clone git@github.com:FluxOfPingIntegers/react-router-nested-routes-code-along
git clone git@github.com:FluxOfPingIntegers/react-simple-state-lab
git clone git@github.com:FluxOfPingIntegers/react-static-components-lab
git clone git@github.com:FluxOfPingIntegers/react-updating-state
git clone git@github.com:FluxOfPingIntegers/react-updating-state-lab
git clone git@github.com:FluxOfPingIntegers/react-using-callbacks-to-pass-information-lab
git clone git@github.com:FluxOfPingIntegers/redux-create-store
git clone git@github.com:FluxOfPingIntegers/redux-create-store-lab
git clone git@github.com:FluxOfPingIntegers/redux-delete-codealong
git clone git@github.com:FluxOfPingIntegers/redux-delete-lab
git clone git@github.com:FluxOfPingIntegers/redux-dispatch
git clone git@github.com:FluxOfPingIntegers/redux-dispatch-with-event-listeners
git clone git@github.com:FluxOfPingIntegers/redux-forms-codealong
git clone git@github.com:FluxOfPingIntegers/redux-index-codealong
git clone git@github.com:FluxOfPingIntegers/redux-initial-dispatch
git clone git@github.com:FluxOfPingIntegers/redux-reducer
git clone git@github.com:FluxOfPingIntegers/redux-thunk-lab
git clone git@github.com:FluxOfPingIntegers/review-map-state-to-props-readme
cd ..