mkdir flatiron
cd flatiron
mkdir mod1
mkdir mod2
mkdir mod3
mkdir mod4
mkdir mod5

cd mod1
git clone git@github.com:FluxOfPingIntegers/020121-Intro-to-Arrays-And-Iteration
git clone git@github.com:FluxOfPingIntegers/looping-while-until
git clone git@github.com:FluxOfPingIntegers/reverse-each-word
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-attribute-accessors-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-has-many-through-lab
git clone git@github.com:FluxOfPingIntegers/anagram-detector
git clone git@github.com:FluxOfPingIntegers/method-arguments-lab
git clone git@github.com:FluxOfPingIntegers/ruby-building-applications-gems-and-bundler
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-classes-and-instances-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-kickstarter-lab
git clone git@github.com:FluxOfPingIntegers/apples-and-holidays
git clone git@github.com:FluxOfPingIntegers/method-scope-lab
git clone git@github.com:FluxOfPingIntegers/ruby-building-applications-requiring-files
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-email-parser-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-my-pets
git clone git@github.com:FluxOfPingIntegers/array-CRUD-lab
git clone git@github.com:FluxOfPingIntegers/my-collect
git clone git@github.com:FluxOfPingIntegers/ruby-building-applications-setting-up-the-environment
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-instance-methods-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-self-cash-register-lab
git clone git@github.com:FluxOfPingIntegers/array-methods-lab
git clone git@github.com:FluxOfPingIntegers/my-each
git clone git@github.com:FluxOfPingIntegers/ruby-getting-remote-data-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-instance-variables-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-self-count-sentences-lab
git clone git@github.com:FluxOfPingIntegers/badges-and-schedules
git clone git@github.com:FluxOfPingIntegers/my-first-hash
git clone git@github.com:FluxOfPingIntegers/ruby-intro-to-hashes-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-object-attributes-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-self-person-lab
git clone git@github.com:FluxOfPingIntegers/building-nested-hashes
git clone git@github.com:FluxOfPingIntegers/my_all
git clone git@github.com:FluxOfPingIntegers/ruby-metaprogramming-custom-errors
git clone git@github.com:FluxOfPingIntegers/ruby-oo-fundamentals-object-initialization-lab
git clone git@github.com:FluxOfPingIntegers/ruby-remote-data-practice-scraping
git clone git@github.com:FluxOfPingIntegers/cartoon-collections
git clone git@github.com:FluxOfPingIntegers/my_find_code_along
git clone git@github.com:FluxOfPingIntegers/ruby-metaprogramming-mass-assignment-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-defining-inheritance
git clone git@github.com:FluxOfPingIntegers/ruby-variable-assignment
git clone git@github.com:FluxOfPingIntegers/collections_practice
git clone git@github.com:FluxOfPingIntegers/nested-hash-iteration-code-along
git clone git@github.com:FluxOfPingIntegers/ruby-metaprogramming-triangle-classification-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-inheritance-lab
git clone git@github.com:FluxOfPingIntegers/say-hello-ruby
git clone git@github.com:FluxOfPingIntegers/countdown-to-midnight
git clone git@github.com:FluxOfPingIntegers/oo-tic-tac-toe
git clone git@github.com:FluxOfPingIntegers/ruby-methods-readme
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-modules
git clone git@github.com:FluxOfPingIntegers/scraping-flatiron-code-along
git clone git@github.com:FluxOfPingIntegers/debugging-with-pry
git clone git@github.com:FluxOfPingIntegers/operators
git clone git@github.com:FluxOfPingIntegers/ruby-music-library-cli
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-modules-lab
git clone git@github.com:FluxOfPingIntegers/scraping-kickstarter
git clone git@github.com:FluxOfPingIntegers/deli-counter
git clone git@github.com:FluxOfPingIntegers/other-hash-methods-code-along
git clone git@github.com:FluxOfPingIntegers/ruby-oo-advanced-class-methods-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-inheritance-super-lab
git clone git@github.com:FluxOfPingIntegers/simple-nesting
git clone git@github.com:FluxOfPingIntegers/getting-remote-data-working-with-apis
git clone git@github.com:FluxOfPingIntegers/oxford-comma
git clone git@github.com:FluxOfPingIntegers/ruby-oo-advanced-class-methods-puppy-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-banking-lab
git clone git@github.com:FluxOfPingIntegers/speaking-grandma
git clone git@github.com:FluxOfPingIntegers/hash-iteration
git clone git@github.com:FluxOfPingIntegers/parrot-ruby
git clone git@github.com:FluxOfPingIntegers/ruby-oo-class-variables-and-class-methods-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-belongs-to-lab
git clone git@github.com:FluxOfPingIntegers/square_array
git clone git@github.com:FluxOfPingIntegers/intro-to-OO
git clone git@github.com:FluxOfPingIntegers/phase1_project
git clone git@github.com:FluxOfPingIntegers/ruby-oo-class-variables-class-constants
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-collaborating-objects-lab
git clone git@github.com:FluxOfPingIntegers/welcome-completing-assignments
git clone git@github.com:FluxOfPingIntegers/key-for-min-value
git clone git@github.com:FluxOfPingIntegers/prime-ruby
git clone git@github.com:FluxOfPingIntegers/ruby-oo-complex-objects-putting-the-pieces-together
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-has-many-lab
git clone git@github.com:FluxOfPingIntegers/yield-and-blocks
git clone git@github.com:FluxOfPingIntegers/looping-times
git clone git@github.com:FluxOfPingIntegers/regex-lab
git clone git@github.com:FluxOfPingIntegers/ruby-oo-complex-objects-school-domain
git clone git@github.com:FluxOfPingIntegers/ruby-oo-object-relationships-has-many-through
git clone git@github.com:FluxOfPingIntegers/yield-and-return-values
cd ..

cd mod2
git clone git@github.com:FluxOfPingIntegers/Phase2_Project
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-issue-bot-9000
git clone git@github.com:FluxOfPingIntegers/nyc-sinatra
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-forms-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-nested-forms
git clone git@github.com:FluxOfPingIntegers/active-record-associations-and-migrations
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-kitten-wheelbarrow-lab
git clone git@github.com:FluxOfPingIntegers/orms-bringing-it-all-together
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-routes-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-nested-forms-lab-superheros
git clone git@github.com:FluxOfPingIntegers/active-record-associations-methods
git clone git@github.com:FluxOfPingIntegers/css-essentials-introduction-to-css-lab
git clone git@github.com:FluxOfPingIntegers/orms-mapping-classes-to-database-tables-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-sessions-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-password-security
git clone git@github.com:FluxOfPingIntegers/active-record-associations-tvland-lab
git clone git@github.com:FluxOfPingIntegers/css-essentials-my-little-rainbow-lab
git clone git@github.com:FluxOfPingIntegers/orms-mapping-database-records-to-ruby-objects-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-basic-views-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-restful-routes-lab
git clone git@github.com:FluxOfPingIntegers/active-record-costume-store-lab
git clone git@github.com:FluxOfPingIntegers/dynamic-orm-inheritance
git clone git@github.com:FluxOfPingIntegers/orms-pokemon-scraper
git clone git@github.com:FluxOfPingIntegers/sinatra-basics
git clone git@github.com:FluxOfPingIntegers/sinatra-secure-password-lab
git clone git@github.com:FluxOfPingIntegers/active-record-crud-operations-lab
git clone git@github.com:FluxOfPingIntegers/dynamic-orm-lab
git clone git@github.com:FluxOfPingIntegers/orms-updating-records-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-complex-forms-associations
git clone git@github.com:FluxOfPingIntegers/sinatra-sessions
git clone git@github.com:FluxOfPingIntegers/active-record-intro-to-rake
git clone git@github.com:FluxOfPingIntegers/dynamic-orms-readme
git clone git@github.com:FluxOfPingIntegers/rack-dynamic-routes-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-dynamic-routes-codealong
git clone git@github.com:FluxOfPingIntegers/sinatra-shotgun-server
git clone git@github.com:FluxOfPingIntegers/active-record-migrations
git clone git@github.com:FluxOfPingIntegers/html-basics-a-tag-with-href-attributes-lab
git clone git@github.com:FluxOfPingIntegers/rack-dynamic-web-apps
git clone git@github.com:FluxOfPingIntegers/sinatra-dynamic-routes-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-user-auth
git clone git@github.com:FluxOfPingIntegers/active-record-querying-methods-lab
git clone git@github.com:FluxOfPingIntegers/html-basics-well-formed-html-document-lab
git clone git@github.com:FluxOfPingIntegers/rack-get-params-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-forms-params-readme-walkthrough
git clone git@github.com:FluxOfPingIntegers/sinatra-view-and-controller-readme-walkthrough
git clone git@github.com:FluxOfPingIntegers/active-record-translating-from-orm-to-ar
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-images-lab
git clone git@github.com:FluxOfPingIntegers/rack-intro
git clone git@github.com:FluxOfPingIntegers/sinatra-from-scratch-readme
git clone git@github.com:FluxOfPingIntegers/sinatra-views
git clone git@github.com:FluxOfPingIntegers/active-record-writing-migrations-lab
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-links-lab
git clone git@github.com:FluxOfPingIntegers/rack-responses-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-hello-world-basics
git clone git@github.com:FluxOfPingIntegers/sinatra-views-lab
git clone git@github.com:FluxOfPingIntegers/basic-sinatra-forms-lab
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-lists-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-activerecord-associations
git clone git@github.com:FluxOfPingIntegers/sinatra-integrating-models-walkthrough
git clone git@github.com:FluxOfPingIntegers/sql-aggregate-functions-lab
git clone git@github.com:FluxOfPingIntegers/code-along
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-html-tables-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-activerecord-setup
git clone git@github.com:FluxOfPingIntegers/sinatra-logging-in-and-out
git clone git@github.com:FluxOfPingIntegers/sql-organizing-bears-lab
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-fundamentals-lab
git clone git@github.com:FluxOfPingIntegers/html-fundamentals-text-formatting-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-activerecord-using-tux
git clone git@github.com:FluxOfPingIntegers/sinatra-mvc-file-structure
git clone git@github.com:FluxOfPingIntegers/sql-table-relations-crowdfunding-join-table-lab
git clone git@github.com:FluxOfPingIntegers/css-essentials-css-graffiti-override-lab
git clone git@github.com:FluxOfPingIntegers/intro-to-capybara
git clone git@github.com:FluxOfPingIntegers/sinatra-ar-crud-lab
git clone git@github.com:FluxOfPingIntegers/sinatra-mvc-lab
git clone git@github.com:FluxOfPingIntegers/sql-table-relations-library-lab
cd ..

cd mod3
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
git clone git@github.com:FluxOfPingIntegers/
